// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package gui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed dupclean_abstract_icon.png
var appLogoData []byte
var appLogo = &fyne.StaticResource{
	StaticName:    "dupclean_abstract_icon.png",
	StaticContent: appLogoData,
}
